//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
    
namespace Smart_install
{
    public partial class DatabaseArchiveEntities : DbContext
    {
        public DatabaseArchiveEntities()
            : base("name=DatabaseArchiveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Archive> Archives { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<SearchProgram> Programs { get; set; }
        public DbSet<System> Systems { get; set; }
        public DbSet<Tag> Tags { get; set; }
    }
}
