//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Smart_install
{
    
    public partial class Archive
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<DateTime> CreateDate { get; set; }
        public Nullable<DateTime> ModifiedDate { get; set; }
        public string Description { get; set; }
    }
}
