//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_install
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArchiveBaseEntities2 : DbContext
    {
        public ArchiveBaseEntities2()
            : base("name=ArchiveBaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Archive> Archives { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Prog> Progs { get; set; }
        public DbSet<systemType> systemTypes { get; set; }
        public DbSet<Tag> Tags { get; set; }
    }
}
