//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart_install
{
    using System;
    using System.Collections.Generic;
    
    public partial class systemType
    {
        public systemType()
        {
            this.Progs = new HashSet<Prog>();
        }
    
        public int Id { get; set; }
        public string systemType1 { get; set; }
    
        public virtual ICollection<Prog> Progs { get; set; }
    }
}
